server:
  port: 9191
spring:
  application:
    name: msvc-cars
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://car_database:3306/carsdb
    username: leo
    password: sqlLeo02
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://msvc-eureka:8761/eureka

gateway:
  auth:
    header: X-GATEWAY-SECRET
    value: key-microservices